# setup-analytics.ps1
# One-command setup for uni-proxy-manager with the analytics extension.
# Usage: .\setup-analytics.ps1 [--no-cache]

$ErrorActionPreference = "Continue"

Push-Location $PSScriptRoot

Write-Host ""
Write-Host "--- Uni-Proxy-Manager: Analytics Extension Setup ---" -ForegroundColor Cyan
Write-Host ""

# Parse optional args (accepts --no-cache, -no-cache, -NoCache, /no-cache)
$noCache = $false
if ($args.Count -gt 0) {
    foreach ($a in $args) {
        if ($a -eq '--no-cache' -or $a -eq '-no-cache' -or $a -eq '-NoCache' -or $a -eq '/no-cache') {
            $noCache = $true
        }
    }
}

# 1. Check Docker is running
Write-Host "[1/5] Checking Docker..." -ForegroundColor Yellow
$dockerCheck = docker info 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker is not running. Please start Docker Desktop and try again." -ForegroundColor Red
    exit 1
}
Write-Host "      Docker is running." -ForegroundColor Green

# 2. Create data directories
Write-Host "[2/5] Creating data directories..." -ForegroundColor Yellow
$dirs = @("data\haproxy", "data\certificates", "data\error-pages")
foreach ($dir in $dirs) {
    $path = Join-Path $PSScriptRoot $dir
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "      Created $dir" -ForegroundColor Gray
    } else {
        Write-Host "      $dir already exists" -ForegroundColor Gray
    }
}

# 3. Generate .env file if it doesn't exist
$envFile = Join-Path $PSScriptRoot ".env"
Write-Host "[3/5] Setting up .env file..." -ForegroundColor Yellow

function New-Secret {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return [Convert]::ToBase64String($bytes)
}

if (Test-Path $envFile) {
    # .env exists -- check if analytics vars are already present
    $envContent = Get-Content $envFile -Raw

    $missing = @()
    if ($envContent -notmatch "UNI_PROXY_MANAGER_CLICKHOUSE_PASSWORD=.+") { $missing += "CLICKHOUSE_PASSWORD" }
    if ($envContent -notmatch "UNI_PROXY_MANAGER_INTERNAL_SECRET=.+") { $missing += "INTERNAL_SECRET" }
    if ($envContent -notmatch "UNI_PROXY_MANAGER_ANALYTICS_JWT_SECRET=.+") { $missing += "ANALYTICS_JWT_SECRET" }

    if ($missing.Count -gt 0) {
        Write-Host "      .env exists but is missing analytics vars: $($missing -join ', ')" -ForegroundColor Gray
        $analyticsBlock = @"

# ===========================================
# Analytics Extension
# ===========================================
"@
        if ($missing -contains "CLICKHOUSE_PASSWORD") {
            $analyticsBlock += "`nUNI_PROXY_MANAGER_CLICKHOUSE_PASSWORD=$(New-Secret)"
        }
        if ($missing -contains "INTERNAL_SECRET") {
            $analyticsBlock += "`nUNI_PROXY_MANAGER_INTERNAL_SECRET=$(New-Secret)"
        }
        if ($missing -contains "ANALYTICS_JWT_SECRET") {
            $analyticsBlock += "`nUNI_PROXY_MANAGER_ANALYTICS_JWT_SECRET=$(New-Secret)"
        }
        Add-Content -Path $envFile -Value $analyticsBlock
        Write-Host "      Appended analytics variables to .env" -ForegroundColor Green
    } else {
        Write-Host "      .env already has all analytics variables" -ForegroundColor Green
    }
} else {
    # No .env -- create one from .env.example with analytics vars filled in
    $apiKey = New-Secret
    $clickhousePassword = New-Secret
    $internalSecret = New-Secret
    $jwtSecret = New-Secret

    $envContent = @"
# ===========================================
# Uni-Proxy-Manager Environment Variables
# ===========================================
# Generated by setup-analytics.ps1

# Application
UNI_PROXY_MANAGER_URL=http://localhost
UNI_PROXY_MANAGER_API_PORT=3001

# Security
UNI_PROXY_MANAGER_API_KEY=$apiKey
UNI_PROXY_MANAGER_AUTH_ENABLED=true
UNI_PROXY_MANAGER_STATS_USER=admin
UNI_PROXY_MANAGER_STATS_PASSWORD=

# Database (PostgreSQL)
UNI_PROXY_MANAGER_DB_USER=uni_proxy_manager
UNI_PROXY_MANAGER_DB_PASSWORD=changeme
UNI_PROXY_MANAGER_DB_NAME=uni_proxy_manager

# Redis
UNI_PROXY_MANAGER_REDIS_URL=redis://redis:6379

# HAProxy
UNI_PROXY_MANAGER_HAPROXY_SOCKET=/var/run/haproxy/haproxy.sock
UNI_PROXY_MANAGER_HAPROXY_CONFIG_PATH=/data/haproxy/haproxy.cfg

# File Storage
UNI_PROXY_MANAGER_CERTS_DIR=/data/certificates
UNI_PROXY_MANAGER_ERROR_PAGES_DIR=/data/error-pages

# ACME / Let's Encrypt
UNI_PROXY_MANAGER_ACME_EMAIL=admin@example.com
UNI_PROXY_MANAGER_ACME_STAGING=true

# Docker Compose
POSTGRES_USER=uni_proxy_manager
POSTGRES_PASSWORD=changeme
POSTGRES_DB=uni_proxy_manager

# ===========================================
# Analytics Extension
# ===========================================
UNI_PROXY_MANAGER_CLICKHOUSE_PASSWORD=$clickhousePassword
UNI_PROXY_MANAGER_INTERNAL_SECRET=$internalSecret
UNI_PROXY_MANAGER_ANALYTICS_JWT_SECRET=$jwtSecret
"@
    Set-Content -Path $envFile -Value $envContent -NoNewline
    Write-Host "      Created .env with generated secrets" -ForegroundColor Green
    Write-Host "      API Key: $apiKey" -ForegroundColor Gray
    Write-Host "      (save this -- you'll need it for API authentication)" -ForegroundColor Gray
}

# 4. Build and start services
Write-Host "[4/5] Building and starting services..." -ForegroundColor Yellow
Write-Host "      This may take a few minutes on first run." -ForegroundColor Gray
Write-Host ""

if ($noCache) {
    Write-Host "      Building with --no-cache" -ForegroundColor Gray
    docker compose -f docker-compose.yml -f docker-compose.analytics.yml build --no-cache
} else {
    Write-Host "      Building using cache" -ForegroundColor Gray
    docker compose -f docker-compose.yml -f docker-compose.analytics.yml build
}

if ($LASTEXITCODE -ne 0) {
    Write-Host "" 
    Write-Host "ERROR: Docker Compose build failed. Check the output above." -ForegroundColor Red
    exit 1
}

docker compose -f docker-compose.yml -f docker-compose.analytics.yml up -d

if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "ERROR: Docker Compose failed. Check the output above." -ForegroundColor Red
    exit 1
}

# 5. Wait for health checks
Write-Host ""
Write-Host "[5/5] Waiting for services to become healthy..." -ForegroundColor Yellow

$services = @("uni-proxy-manager-postgres", "uni-proxy-manager-redis", "uni-proxy-manager-clickhouse", "uni-proxy-manager-api", "uni-proxy-manager-analytics")
$timeout = 120
$start = Get-Date

foreach ($svc in $services) {
    $svcName = $svc -replace "uni-proxy-manager-", ""
    Write-Host "      Waiting for $svcName..." -ForegroundColor Gray -NoNewline

    while ($true) {
        $elapsed = ((Get-Date) - $start).TotalSeconds
        if ($elapsed -gt $timeout) {
            Write-Host " TIMEOUT" -ForegroundColor Red
            Write-Host ""
            Write-Host "Some services didn't become healthy within ${timeout}s." -ForegroundColor Red
            Write-Host "Run 'docker compose -f docker-compose.yml -f docker-compose.analytics.yml logs' to investigate." -ForegroundColor Yellow
            exit 1
        }

        $health = docker inspect --format "{{.State.Health.Status}}" $svc 2>$null
        if ($health -eq "healthy") {
            Write-Host " OK" -ForegroundColor Green
            break
        }
        Start-Sleep -Seconds 2
    }
}

# Done
Write-Host ""
Write-Host "--- Setup Complete ---" -ForegroundColor Green
Write-Host ""
Write-Host "  Dashboard:       http://localhost:3000" -ForegroundColor White
Write-Host "  HAProxy Stats:   http://localhost:8404/stats" -ForegroundColor White
Write-Host "  Analytics (int): http://localhost:3003/health (internal only)" -ForegroundColor White
Write-Host ""
Write-Host "  Useful commands:" -ForegroundColor White
Write-Host "    Logs:    docker compose -f docker-compose.yml -f docker-compose.analytics.yml logs -f" -ForegroundColor Gray
Write-Host "    Stop:    docker compose -f docker-compose.yml -f docker-compose.analytics.yml down" -ForegroundColor Gray
Write-Host "    Restart: docker compose -f docker-compose.yml -f docker-compose.analytics.yml restart" -ForegroundColor Gray
Write-Host ""
