import {
  pgTable,
  text,
  timestamp,
  pgEnum,
  integer,
} from "drizzle-orm/pg-core";

export const errorPageTypeEnum = pgEnum("error_page_type", [
  "503",           // Service unavailable (backend down)
  "404",           // Not found
  "500",           // Internal server error
  "502",           // Bad gateway
  "504",           // Gateway timeout
  "maintenance",   // Manual maintenance mode
  "custom",        // Custom error code
]);

export const errorPages = pgTable("error_pages", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  type: errorPageTypeEnum("type").notNull(),
  httpStatusCode: integer("http_status_code"), // For custom type (e.g., 500, 502, 504)

  // Storage path (relative to error-pages volume)
  directoryPath: text("directory_path").notNull(),
  entryFile: text("entry_file").notNull().default("index.html"),

  // File info
  originalZipName: text("original_zip_name"),
  uploadedAt: timestamp("uploaded_at"),
  fileSize: integer("file_size"), // Total extracted size in bytes
  fileCount: integer("file_count"), // Number of files in the archive

  // Description for UI
  description: text("description"),

  // Preview image path (generated by Playwright)
  previewImagePath: text("preview_image_path"),

  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export type ErrorPage = typeof errorPages.$inferSelect;
export type NewErrorPage = typeof errorPages.$inferInsert;
